export const CUSTOMER_LANGUAGES = [
  { language: "Marathi", code: "mr-IN" },
  { language: "Hindi", code: "hi-IN" },
  { language: "English", code: "en-IN" },
  { language: "Gujarati", code: "gu-IN" },
  { language: "Kannada", code: "kn-IN" },
  { language: "Tamil", code: "ta-IN" },
  { language: "Telugu", code: "te-IN" },
  { language: "Bengali", code: "bn-IN" },
  { language: "Malayalam", code: "ml-IN" },
  { language: "Punjabi", code: "pa-IN" },
] as const;

export type CustomerLanguageCode = typeof CUSTOMER_LANGUAGES[number]["code"];
export const DEFAULT_CUSTOMER_LANGUAGE_CODE: CustomerLanguageCode = "mr-IN";
export const DEFAULT_CUSTOMER_LANGUAGE = CUSTOMER_LANGUAGES.find(
  (item) => item.code === DEFAULT_CUSTOMER_LANGUAGE_CODE,
) ?? CUSTOMER_LANGUAGES[0];

type KioskCopy = {
  speakingToday: string;
  startPrompt: string;
  listenPrompt: string;
  speakingPrompt: string;
  canSpeakNow: string;
  aiThinking: string;
  aiSpeaking: string;
  listening: string;
  activeSession: string;
  tapToStart: string;
  waitingForVoice: string;
  pleaseSpeak: string;
  pleaseListen: string;
  formCompleteTitle: string;
  formCompleteBody: string;
  viewCompletedForm: string;
};

const COPY: Record<string, KioskCopy> = {
  "en-IN": {
    speakingToday: "We're speaking English today.",
    startPrompt: "Tap the microphone once to begin",
    listenPrompt: "I am listening",
    speakingPrompt: "Please listen",
    canSpeakNow: "You can speak now",
    aiThinking: "AI is thinking...",
    aiSpeaking: "AI Speaking",
    listening: "Listening...",
    activeSession: "Active Session",
    tapToStart: "Tap to Start",
    waitingForVoice: "Waiting for voice",
    pleaseSpeak: "Please speak",
    pleaseListen: "Please listen",
    formCompleteTitle: "Thank you!",
    formCompleteBody: "Your form is complete.",
    viewCompletedForm: "View completed form",
  },
  "mr-IN": {
    speakingToday: "आज आपण मराठीत बोलत आहोत.",
    startPrompt: "सुरू करण्यासाठी मायक्रोफोन दाबा",
    listenPrompt: "मी ऐकत आहे",
    speakingPrompt: "कृपया ऐका",
    canSpeakNow: "आता बोला",
    aiThinking: "AI विचार करत आहे...",
    aiSpeaking: "AI बोलत आहे",
    listening: "ऐकत आहे...",
    activeSession: "सत्र सुरू आहे",
    tapToStart: "सुरू करा",
    waitingForVoice: "आवाजाची वाट पाहत आहे",
    pleaseSpeak: "कृपया बोला",
    pleaseListen: "कृपया ऐका",
    formCompleteTitle: "धन्यवाद!",
    formCompleteBody: "तुमचा फॉर्म पूर्ण झाला आहे.",
    viewCompletedForm: "पूर्ण फॉर्म पहा",
  },
  "hi-IN": {
    speakingToday: "आज हम हिंदी में बात कर रहे हैं.",
    startPrompt: "शुरू करने के लिए माइक्रोफोन दबाएँ",
    listenPrompt: "मैं सुन रहा हूँ",
    speakingPrompt: "कृपया सुनें",
    canSpeakNow: "अब बोलिए",
    aiThinking: "AI सोच रहा है...",
    aiSpeaking: "AI बोल रहा है",
    listening: "सुन रहा है...",
    activeSession: "सत्र चालू है",
    tapToStart: "शुरू करें",
    waitingForVoice: "आवाज़ की प्रतीक्षा है",
    pleaseSpeak: "कृपया बोलें",
    pleaseListen: "कृपया सुनें",
    formCompleteTitle: "धन्यवाद!",
    formCompleteBody: "आपका फॉर्म पूरा हो गया है.",
    viewCompletedForm: "पूरा फॉर्म देखें",
  },
  "gu-IN": {
    speakingToday: "આજે આપણે ગુજરાતીમાં વાત કરી રહ્યા છીએ.",
    startPrompt: "શરૂ કરવા માટે માઇક્રોફોન દબાવો",
    listenPrompt: "હું સાંભળી રહ્યો છું",
    speakingPrompt: "કૃપા કરીને સાંભળો",
    canSpeakNow: "હવે બોલો",
    aiThinking: "AI વિચાર કરી રહ્યું છે...",
    aiSpeaking: "AI બોલી રહ્યું છે",
    listening: "સાંભળી રહ્યું છે...",
    activeSession: "સત્ર ચાલુ છે",
    tapToStart: "શરૂ કરો",
    waitingForVoice: "અવાજની રાહ જોઈ રહ્યું છે",
    pleaseSpeak: "કૃપા કરીને બોલો",
    pleaseListen: "કૃપા કરીને સાંભળો",
    formCompleteTitle: "આભાર!",
    formCompleteBody: "તમારું ફોર્મ પૂર્ણ થયું છે.",
    viewCompletedForm: "પૂર્ણ ફોર્મ જુઓ",
  },
  "kn-IN": {
    speakingToday: "ಇಂದು ನಾವು ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡುತ್ತಿದ್ದೇವೆ.",
    startPrompt: "ಪ್ರಾರಂಭಿಸಲು ಮೈಕ್ರೊಫೋನ್ ಒತ್ತಿ",
    listenPrompt: "ನಾನು ಕೇಳುತ್ತಿದ್ದೇನೆ",
    speakingPrompt: "ದಯವಿಟ್ಟು ಕೇಳಿ",
    canSpeakNow: "ಈಗ ಮಾತನಾಡಿ",
    aiThinking: "AI ಯೋಚಿಸುತ್ತಿದೆ...",
    aiSpeaking: "AI ಮಾತನಾಡುತ್ತಿದೆ",
    listening: "ಕೇಳುತ್ತಿದೆ...",
    activeSession: "ಸೆಷನ್ ಸಕ್ರಿಯವಾಗಿದೆ",
    tapToStart: "ಪ್ರಾರಂಭಿಸಿ",
    waitingForVoice: "ಧ್ವನಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ",
    pleaseSpeak: "ದಯವಿಟ್ಟು ಮಾತನಾಡಿ",
    pleaseListen: "ದಯವಿಟ್ಟು ಕೇಳಿ",
    formCompleteTitle: "ಧನ್ಯವಾದಗಳು!",
    formCompleteBody: "ನಿಮ್ಮ ಫಾರ್ಮ್ ಪೂರ್ಣಗೊಂಡಿದೆ.",
    viewCompletedForm: "ಪೂರ್ಣಗೊಂಡ ಫಾರ್ಮ್ ನೋಡಿ",
  },
  "ta-IN": {
    speakingToday: "இன்று நாம் தமிழில் பேசுகிறோம்.",
    startPrompt: "தொடங்க மைக்ரோஃபோனை அழுத்தவும்",
    listenPrompt: "நான் கேட்கிறேன்",
    speakingPrompt: "தயவுசெய்து கேளுங்கள்",
    canSpeakNow: "இப்போது பேசலாம்",
    aiThinking: "AI யோசிக்கிறது...",
    aiSpeaking: "AI பேசுகிறது",
    listening: "கேட்கிறது...",
    activeSession: "அமர்வு செயலில் உள்ளது",
    tapToStart: "தொடங்கு",
    waitingForVoice: "குரலை காத்திருக்கிறது",
    pleaseSpeak: "தயவுசெய்து பேசுங்கள்",
    pleaseListen: "தயவுசெய்து கேளுங்கள்",
    formCompleteTitle: "நன்றி!",
    formCompleteBody: "உங்கள் படிவம் முடிந்தது.",
    viewCompletedForm: "முடிந்த படிவத்தைப் பாருங்கள்",
  },
  "te-IN": {
    speakingToday: "ఈ రోజు మనం తెలుగులో మాట్లాడుతున్నాం.",
    startPrompt: "ప్రారంభించడానికి మైక్రోఫోన్ నొక్కండి",
    listenPrompt: "నేను వింటున్నాను",
    speakingPrompt: "దయచేసి వినండి",
    canSpeakNow: "ఇప్పుడు మాట్లాడండి",
    aiThinking: "AI ఆలోచిస్తోంది...",
    aiSpeaking: "AI మాట్లాడుతోంది",
    listening: "వింటోంది...",
    activeSession: "సెషన్ సక్రియంగా ఉంది",
    tapToStart: "ప్రారంభించండి",
    waitingForVoice: "వాయిస్ కోసం ఎదురుచూస్తోంది",
    pleaseSpeak: "దయచేసి మాట్లాడండి",
    pleaseListen: "దయచేసి వినండి",
    formCompleteTitle: "ధన్యవాదాలు!",
    formCompleteBody: "మీ ఫారమ్ పూర్తయింది.",
    viewCompletedForm: "పూర్తయిన ఫారమ్ చూడండి",
  },
  "bn-IN": {
    speakingToday: "আজ আমরা বাংলায় কথা বলছি।",
    startPrompt: "শুরু করতে মাইক্রোফোন চাপুন",
    listenPrompt: "আমি শুনছি",
    speakingPrompt: "অনুগ্রহ করে শুনুন",
    canSpeakNow: "এখন বলুন",
    aiThinking: "AI ভাবছে...",
    aiSpeaking: "AI বলছে",
    listening: "শুনছে...",
    activeSession: "সেশন চলছে",
    tapToStart: "শুরু করুন",
    waitingForVoice: "কণ্ঠস্বরের অপেক্ষায়",
    pleaseSpeak: "অনুগ্রহ করে বলুন",
    pleaseListen: "অনুগ্রহ করে শুনুন",
    formCompleteTitle: "ধন্যবাদ!",
    formCompleteBody: "আপনার ফর্ম সম্পূর্ণ হয়েছে।",
    viewCompletedForm: "সম্পূর্ণ ফর্ম দেখুন",
  },
  "ml-IN": {
    speakingToday: "ഇന്ന് നാം മലയാളത്തിൽ സംസാരിക്കുന്നു.",
    startPrompt: "തുടങ്ങാൻ മൈക്രോഫോൺ അമർത്തുക",
    listenPrompt: "ഞാൻ കേൾക്കുന്നു",
    speakingPrompt: "ദയവായി കേൾക്കൂ",
    canSpeakNow: "ഇപ്പോൾ സംസാരിക്കാം",
    aiThinking: "AI ചിന്തിക്കുന്നു...",
    aiSpeaking: "AI സംസാരിക്കുന്നു",
    listening: "കേൾക്കുന്നു...",
    activeSession: "സെഷൻ സജീവമാണ്",
    tapToStart: "തുടങ്ങുക",
    waitingForVoice: "ശബ്ദത്തിനായി കാത്തിരിക്കുന്നു",
    pleaseSpeak: "ദയവായി സംസാരിക്കുക",
    pleaseListen: "ദയവായി കേൾക്കൂ",
    formCompleteTitle: "നന്ദി!",
    formCompleteBody: "നിങ്ങളുടെ ഫോം പൂർത്തിയായി.",
    viewCompletedForm: "പൂർത്തിയായ ഫോം കാണുക",
  },
  "pa-IN": {
    speakingToday: "ਅੱਜ ਅਸੀਂ ਪੰਜਾਬੀ ਵਿੱਚ ਗੱਲ ਕਰ ਰਹੇ ਹਾਂ।",
    startPrompt: "ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਮਾਈਕ੍ਰੋਫੋਨ ਦਬਾਓ",
    listenPrompt: "ਮੈਂ ਸੁਣ ਰਿਹਾ ਹਾਂ",
    speakingPrompt: "ਕਿਰਪਾ ਕਰਕੇ ਸੁਣੋ",
    canSpeakNow: "ਹੁਣ ਬੋਲੋ",
    aiThinking: "AI ਸੋਚ ਰਿਹਾ ਹੈ...",
    aiSpeaking: "AI ਬੋਲ ਰਿਹਾ ਹੈ",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ...",
    activeSession: "ਸੈਸ਼ਨ ਚਾਲੂ ਹੈ",
    tapToStart: "ਸ਼ੁਰੂ ਕਰੋ",
    waitingForVoice: "ਆਵਾਜ਼ ਦੀ ਉਡੀਕ ਹੈ",
    pleaseSpeak: "ਕਿਰਪਾ ਕਰਕੇ ਬੋਲੋ",
    pleaseListen: "ਕਿਰਪਾ ਕਰਕੇ ਸੁਣੋ",
    formCompleteTitle: "ਧੰਨਵਾਦ!",
    formCompleteBody: "ਤੁਹਾਡਾ ਫਾਰਮ ਪੂਰਾ ਹੋ ਗਿਆ ਹੈ।",
    viewCompletedForm: "ਪੂਰਾ ਫਾਰਮ ਵੇਖੋ",
  },
};

export function kioskCopy(languageCode: string): KioskCopy {
  return COPY[languageCode] ?? COPY["en-IN"];
}
